from django.db import models


# Create your models here.
class DataTable(models.Model):
    auto_id = models.AutoField(verbose_name='序号', primary_key=True)
    field1 = models.CharField(verbose_name='线别', max_length=200)
    field2 = models.CharField(verbose_name='综合车间', max_length=200)
    field3 = models.CharField(verbose_name='车站及区间名称', max_length=200)
    field48 = models.CharField(verbose_name='运营区段名', max_length=200)
    field37 = models.CharField(verbose_name='标称载频', max_length=200)
    field50 = models.CharField(verbose_name='区段长度', max_length=200)
    field54 = models.CharField(verbose_name='电容数量', max_length=200)
    field85 = models.CharField(verbose_name='室内送端电压发送器功出电压(V)', max_length=200)
    field86 = models.CharField(verbose_name='室内送端电压模拟网设备侧电压(V)', max_length=200)
    field87 = models.CharField(verbose_name='室内送端电压模拟网电缆侧电压(V)', max_length=200)
    field88 = models.CharField(verbose_name='室外送端电压匹配变压器电缆侧电压(V)', max_length=200)
    field89 = models.CharField(verbose_name='室外送端电压匹配变压器轨面侧电压(V)', max_length=200)
    field90 = models.CharField(verbose_name='室外送端电压轨面电压(V)', max_length=200)
    field91 = models.CharField(verbose_name='室外受端(主轨)', max_length=200)
    field92 = models.CharField(verbose_name='电压轨面电压(V)', max_length=200)
    field93 = models.CharField(verbose_name='室外受端(主轨)', max_length=200)
    field94 = models.CharField(verbose_name='电压匹配变压器轨面侧电压(V)', max_length=200)
    field95 = models.CharField(verbose_name='室外受端(主轨)', max_length=200)
    field96 = models.CharField(verbose_name='电压匹配变压器电缆侧电压(V)', max_length=200)
    field97 = models.CharField(verbose_name='室内受端(主轨)', max_length=200)
    field98 = models.CharField(verbose_name='电压模拟网电缆侧电压(mV)', max_length=200)
    field99 = models.CharField(verbose_name='室内受端(主轨)', max_length=200)
    field100 = models.CharField(verbose_name='电压模拟网设备侧电压(mV)', max_length=200)
    field101 = models.CharField(verbose_name='室内受端(主轨)', max_length=200)
    field102 = models.CharField(verbose_name='电压衰耗器轨入电压(mV)', max_length=200)
    field103 = models.CharField(verbose_name='室内受端(主轨)', max_length=200)
    field104 = models.CharField(verbose_name='电压衰耗器轨出1电压(mV)', max_length=200)
    field105 = models.CharField(verbose_name='室内受端(主轨)', max_length=200)
    field106 = models.CharField(verbose_name='电压衰耗器GJ(Z)', max_length=200)
    field107 = models.CharField(verbose_name='电压(mV)', max_length=200)
    field108 = models.CharField(verbose_name='室内受端(主轨)', max_length=200)
    field109 = models.CharField(verbose_name='电压衰耗器GJ(B)', max_length=200)
    field110 = models.CharField(verbose_name='电压(mV)', max_length=200)
