# Generated by Django 3.0.7 on 2020-10-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
                ('field2', models.CharField(max_length=200)),
                ('field3', models.CharField(max_length=200)),
                ('field48', models.CharField(max_length=200)),
                ('field37', models.CharField(max_length=200)),
                ('field50', models.CharField(max_length=200)),
                ('field54', models.CharField(max_length=200)),
                ('field85', models.CharField(max_length=200)),
                ('field86', models.CharField(max_length=200)),
                ('field87', models.CharField(max_length=200)),
                ('field88', models.CharField(max_length=200)),
                ('field89', models.CharField(max_length=200)),
                ('field90', models.CharField(max_length=200)),
                ('field91', models.CharField(max_length=200)),
                ('field92', models.CharField(max_length=200)),
                ('field93', models.CharField(max_length=200)),
                ('field94', models.CharField(max_length=200)),
                ('field95', models.CharField(max_length=200)),
                ('field96', models.CharField(max_length=200)),
                ('field97', models.CharField(max_length=200)),
                ('field98', models.CharField(max_length=200)),
                ('field99', models.CharField(max_length=200)),
                ('field100', models.CharField(max_length=200)),
                ('field101', models.CharField(max_length=200)),
                ('field102', models.CharField(max_length=200)),
                ('field103', models.CharField(max_length=200)),
                ('field104', models.CharField(max_length=200)),
                ('field105', models.CharField(max_length=200)),
                ('field106', models.CharField(max_length=200)),
                ('field107', models.CharField(max_length=200)),
                ('field108', models.CharField(max_length=200)),
                ('field109', models.CharField(max_length=200)),
                ('field110', models.CharField(max_length=200)),
            ],
        ),
    ]
