# Generated by Django 3.0.8 on 2021-01-28 08:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model4', '0001_initial'),
        ]

    operations = [
        migrations.AlterField(
                model_name='datatable',
                name='auto_id',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field1',
                field=models.CharField(max_length=200, verbose_name='线别'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field100',
                field=models.CharField(max_length=200, verbose_name='电压模拟网设备侧电压(mV)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field101',
                field=models.CharField(max_length=200, verbose_name='室内受端(主轨)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field102',
                field=models.CharField(max_length=200, verbose_name='电压衰耗器轨入电压(mV)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field103',
                field=models.CharField(max_length=200, verbose_name='室内受端(主轨)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field104',
                field=models.CharField(max_length=200, verbose_name='电压衰耗器轨出1电压(mV)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field105',
                field=models.CharField(max_length=200, verbose_name='室内受端(主轨)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field106',
                field=models.CharField(max_length=200, verbose_name='电压衰耗器GJ(Z)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field107',
                field=models.CharField(max_length=200, verbose_name='电压(mV)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field108',
                field=models.CharField(max_length=200, verbose_name='室内受端(主轨)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field109',
                field=models.CharField(max_length=200, verbose_name='电压衰耗器GJ(B)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field110',
                field=models.CharField(max_length=200, verbose_name='电压(mV)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field2',
                field=models.CharField(max_length=200, verbose_name='综合车间'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field3',
                field=models.CharField(max_length=200, verbose_name='车站及区间名称'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field37',
                field=models.CharField(max_length=200, verbose_name='标称载频'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field48',
                field=models.CharField(max_length=200, verbose_name='运营区段名'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field50',
                field=models.CharField(max_length=200, verbose_name='区段长度'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field54',
                field=models.CharField(max_length=200, verbose_name='电容数量'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field85',
                field=models.CharField(max_length=200, verbose_name='室内送端电压发送器功出电压(V)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field86',
                field=models.CharField(max_length=200, verbose_name='室内送端电压模拟网设备侧电压(V)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field87',
                field=models.CharField(max_length=200, verbose_name='室内送端电压模拟网电缆侧电压(V)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field88',
                field=models.CharField(max_length=200, verbose_name='室外送端电压匹配变压器电缆侧电压(V)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field89',
                field=models.CharField(max_length=200, verbose_name='室外送端电压匹配变压器轨面侧电压(V)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field90',
                field=models.CharField(max_length=200, verbose_name='室外送端电压轨面电压(V)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field91',
                field=models.CharField(max_length=200, verbose_name='室外受端(主轨)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field92',
                field=models.CharField(max_length=200, verbose_name='电压轨面电压(V)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field93',
                field=models.CharField(max_length=200, verbose_name='室外受端(主轨)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field94',
                field=models.CharField(max_length=200, verbose_name='电压匹配变压器轨面侧电压(V)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field95',
                field=models.CharField(max_length=200, verbose_name='室外受端(主轨)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field96',
                field=models.CharField(max_length=200, verbose_name='电压匹配变压器电缆侧电压(V)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field97',
                field=models.CharField(max_length=200, verbose_name='室内受端(主轨)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field98',
                field=models.CharField(max_length=200, verbose_name='电压模拟网电缆侧电压(mV)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field99',
                field=models.CharField(max_length=200, verbose_name='室内受端(主轨)'),
                ),
        ]
