from django.db import models


# Create your models here.
class DataTable(models.Model):
    auto_id = models.AutoField(primary_key=True)
    field1 = models.CharField(max_length=200)
    field2 = models.CharField(max_length=200)
    field3 = models.CharField(max_length=200)
    field24 = models.CharField(max_length=200)
    field23 = models.CharField(max_length=200)
    field46 = models.CharField(max_length=200)
    field47 = models.CharField(max_length=200)
    field48 = models.CharField(max_length=200)
    field49 = models.CharField(max_length=200)
    field37 = models.CharField(max_length=200)
    field50 = models.CharField(max_length=200)
    field51 = models.CharField(max_length=200)
    field52 = models.CharField(max_length=200)
    field53 = models.CharField(max_length=200)
    field54 = models.CharField(max_length=200)
    field55 = models.CharField(max_length=200)
    field56 = models.CharField(max_length=200)
    field57 = models.CharField(max_length=200)
    field58 = models.CharField(max_length=200)
    field59 = models.CharField(max_length=200)
    field60 = models.CharField(max_length=200)
    field61 = models.CharField(max_length=200)
    field62 = models.CharField(max_length=200)
    field63 = models.CharField(max_length=200)
    field64 = models.CharField(max_length=200)
    field65 = models.CharField(max_length=200)
    field66 = models.CharField(max_length=200)
    field67 = models.CharField(max_length=200)
    field68 = models.CharField(max_length=200)
    field69 = models.CharField(max_length=200)
    field71 = models.CharField(max_length=200)
    field72 = models.CharField(max_length=200)
    field73 = models.CharField(max_length=200)
    field74 = models.CharField(max_length=200)
    field75 = models.CharField(max_length=200)
    field76 = models.CharField(max_length=200)
    field77 = models.CharField(max_length=200)
    field78 = models.CharField(max_length=200)
    field79 = models.CharField(max_length=200)
    field80 = models.CharField(max_length=200)
    field81 = models.CharField(max_length=200)
    field82 = models.CharField(max_length=200)
    field83 = models.CharField(max_length=200)
    field84 = models.CharField(max_length=200)


class Field71Table(models.Model):
    """轨道类型"""
    auto_id = models.AutoField(primary_key=True)
    field1 = models.CharField(max_length=200)
