from django.db import models


# Create your models here.
class DataTable(models.Model):
    auto_id = models.AutoField(verbose_name='序号', primary_key=True)
    field1 = models.CharField(verbose_name='线别', max_length=200)
    field2 = models.CharField(verbose_name='车间', max_length=200)
    field3 = models.CharField(verbose_name='车站', max_length=200)
    field24 = models.CharField(verbose_name='站内区间', max_length=200)
    field23 = models.CharField(verbose_name='行别', max_length=200)
    field46 = models.CharField(verbose_name='信号机名称', max_length=200)
    field48 = models.CharField(verbose_name='信号机里程', max_length=200)
    field47 = models.CharField(verbose_name='运营区段名', max_length=200)
    field49 = models.CharField(verbose_name='设计区段名', max_length=200)
    field37 = models.CharField(verbose_name='载频频率', max_length=200)
    field50 = models.CharField(verbose_name='区段长度', max_length=200)
    field51 = models.CharField(verbose_name='段属', max_length=200)
    field52 = models.CharField(verbose_name='备注1', max_length=200)
    field53 = models.CharField(verbose_name='电容规格', max_length=200)
    field54 = models.CharField(verbose_name='电容数量', max_length=200)
    field55 = models.CharField(verbose_name='功出电平理论等级', max_length=200)
    field56 = models.CharField(verbose_name='功出电平理论封线', max_length=200)
    field57 = models.CharField(verbose_name='功出电平变更等级', max_length=200)
    field58 = models.CharField(verbose_name='功出电平变更封线', max_length=200)
    field59 = models.CharField(verbose_name='接收电平理论等级', max_length=200)
    field60 = models.CharField(verbose_name='接收电平理论封线', max_length=200)
    field61 = models.CharField(verbose_name='接收电平变更等级', max_length=200)
    field62 = models.CharField(verbose_name='接收电平变更封线', max_length=200)
    field63 = models.CharField(verbose_name='轨道类型', max_length=200)
    field64 = models.CharField(verbose_name='电缆规定总长度km', max_length=200)
    field65 = models.CharField(verbose_name='发送模拟电缆环阻', max_length=200)
    field66 = models.CharField(verbose_name='发送模拟电缆电缆长度', max_length=200)
    field67 = models.CharField(verbose_name='发送模拟电缆实际电缆长度档位', max_length=200)
    field68 = models.CharField(verbose_name='发送模拟电缆模拟长度', max_length=200)
    field69 = models.CharField(verbose_name='发送模拟电缆模拟固定长度', max_length=200)
    field71 = models.CharField(verbose_name='发送模拟电缆补偿连接线', max_length=200)
    field72 = models.CharField(verbose_name='接收模拟电缆环阻', max_length=200)
    field73 = models.CharField(verbose_name='接收模拟电缆电缆长度', max_length=200)
    field74 = models.CharField(verbose_name='接收模拟电缆实际电缆长度档位', max_length=200)
    field75 = models.CharField(verbose_name='接收模拟电缆模拟长度', max_length=200)
    field76 = models.CharField(verbose_name='接收模拟电缆模拟固定长度', max_length=200)
    field77 = models.CharField(verbose_name='接收模拟电缆补偿连接线', max_length=200)
    field78 = models.CharField(verbose_name='调整表固定区段', max_length=200)
    field79 = models.CharField(verbose_name='有无小轨', max_length=200)
    field80 = models.CharField(verbose_name='小轨调整正向等级', max_length=200)
    field81 = models.CharField(verbose_name='小轨调整正向封线', max_length=200)
    field82 = models.CharField(verbose_name='小轨调整反向等级', max_length=200)
    field83 = models.CharField(verbose_name='小轨调整反向封线', max_length=200)
    field84 = models.CharField(verbose_name='备注2', max_length=200)


class Field71Table(models.Model):
    """轨道类型"""
    auto_id = models.AutoField(verbose_name='序号', primary_key=True)
    field1 = models.CharField(verbose_name='轨道类型', max_length=200)
    changdu = models.CharField(verbose_name='电缆规定总长度', max_length=100, default='', null=True)
