# Generated by Django 3.0.8 on 2020-12-15 07:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_auto_20201215_1459'),
        ]

    operations = [
        migrations.AlterField(
                model_name='basicinfo',
                name='email',
                field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
                ),
        ]
