# Generated by Django 3.0.7 on 2020-11-19 13:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ]

    operations = [
        migrations.CreateModel(
            name='PartTable',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('pn', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='零件号')),
                ('part_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='零件名称')),
                ('car_type', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='车型')),
                ('producer', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='供应商')),
                ('receive_date',
                 models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='到件时间')),
                ('batch', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='批次')),
                (
                    'send_people',
                    models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='送件人')),
                ('contact', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='联系方式')),
                (
                    'save_count',
                    models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='库存数量')),
                ('receive_people',
                 models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='接收人')),
                ('deal_mode', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='处理方式')),
                (
                    'deal_count',
                    models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='报废数量')),
                ('deal_remark',
                 models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='取走人及电话')),
                ('deal_date', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='取走时间')),
                ('qrcode', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='二维码')),
                ('use', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='零件用途')),
                ],
            ),
        ]
