# Generated by Django 3.0.7 on 2021-02-05 08:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model2', '0002_auto_20210128_1656'),
        ]

    operations = [
        migrations.AlterField(
                model_name='datatable',
                name='field3',
                field=models.CharField(max_length=200, verbose_name='车站'),
                ),
        ]
