# Generated by Django 3.0.7 on 2020-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_table',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
                ('field2', models.CharField(max_length=200)),
                ('field3', models.CharField(max_length=200)),
                ('field4', models.CharField(max_length=200)),
                ('field5', models.CharField(max_length=200)),
                ('field6', models.CharField(max_length=200)),
                ('field7', models.CharField(max_length=200)),
                ('field8', models.CharField(max_length=200)),
                ('field9', models.CharField(max_length=200)),
                ('field10', models.CharField(max_length=200)),
                ('field11', models.CharField(max_length=200)),
                ('field12', models.CharField(max_length=200)),
                ('field13', models.CharField(max_length=200)),
                ('field14', models.CharField(max_length=200)),
                ('field15', models.CharField(max_length=200)),
                ('field16', models.CharField(max_length=200)),
                ('field17', models.CharField(max_length=200)),
                ('field18', models.CharField(max_length=200)),
                ('field19', models.CharField(max_length=200)),
                ('field20', models.CharField(max_length=200)),
                ('field21', models.CharField(max_length=200)),
                ('field22', models.CharField(max_length=200)),
                ('field23', models.CharField(max_length=200)),
                ('field24', models.CharField(max_length=200)),
                ('field25', models.CharField(max_length=200)),
                ('field26', models.CharField(max_length=200)),
                ('field27', models.CharField(max_length=200)),
                ('field28', models.CharField(max_length=200)),
                ('field29', models.CharField(max_length=200)),
            ],
        ),
    ]
