# Generated by Django 3.0.7 on 2020-08-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='field1',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='field2',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='field23',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='field24',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='field25',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='field26',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='field27',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='field3',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
            ],
        ),
    ]
