# Generated by Django 3.0.7 on 2020-08-12 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Model', '0002_field1_field2_field23_field24_field25_field26_field27_field3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data_table',
            new_name='DataTable',
        ),
        migrations.RenameModel(
            old_name='field3',
            new_name='Field1Table',
        ),
        migrations.RenameModel(
            old_name='field27',
            new_name='Field23Table',
        ),
        migrations.RenameModel(
            old_name='field1',
            new_name='Field24Table',
        ),
        migrations.RenameModel(
            old_name='field25',
            new_name='Field25Table',
        ),
        migrations.RenameModel(
            old_name='field23',
            new_name='Field26Table',
        ),
        migrations.RenameModel(
            old_name='field26',
            new_name='Field27Table',
        ),
        migrations.RenameModel(
            old_name='field24',
            new_name='Field2Table',
        ),
        migrations.RenameModel(
            old_name='field2',
            new_name='Field3Table',
        ),
    ]
