# Generated by Django 3.0.8 on 2020-09-21 02:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model', '0001_initial'),
        ]

    operations = [
        migrations.AlterField(
                model_name='datatable',
                name='field70',
                field=models.CharField(max_length=200),
                ),
        ]
