# Generated by Django 3.0.7 on 2020-12-15 12:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model', '0002_auto_20200921_1002'),
        ]

    operations = [
        migrations.AlterField(
                model_name='field1table',
                name='field1',
                field=models.CharField(max_length=200, unique=True),
                ),
        migrations.AlterField(
                model_name='field2table',
                name='field1',
                field=models.CharField(max_length=200, unique=True),
                ),
        ]
