# Generated by Django 3.0.8 on 2021-01-28 08:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model', '0003_auto_20201215_2027'),
        ]

    operations = [
        migrations.AlterField(
                model_name='datatable',
                name='field1',
                field=models.CharField(max_length=200, verbose_name='线别'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field10',
                field=models.CharField(max_length=200, verbose_name='曲线半径'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field11',
                field=models.CharField(max_length=200, verbose_name='曲线外轨超高'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field12',
                field=models.CharField(max_length=200, verbose_name='本线曲线内侧'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field13',
                field=models.CharField(max_length=200, verbose_name='本线曲线外侧'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field14',
                field=models.CharField(max_length=200, verbose_name='邻线曲线内侧'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field15',
                field=models.CharField(max_length=200, verbose_name='邻线曲线外侧'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field16',
                field=models.CharField(max_length=200, verbose_name='本线标准值'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field17',
                field=models.CharField(max_length=200, verbose_name='邻线标准值'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field18',
                field=models.CharField(max_length=200, verbose_name='备注'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field19',
                field=models.CharField(max_length=200, verbose_name='本线实测值与标准值只差'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field2',
                field=models.CharField(max_length=200, verbose_name='综合车间'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field20',
                field=models.CharField(max_length=200, verbose_name='邻线实测值与标准值只差'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field21',
                field=models.CharField(max_length=200, verbose_name='本线数据是否超限'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field22',
                field=models.CharField(max_length=200, verbose_name='邻线数据是否超限'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field24',
                field=models.CharField(max_length=200, verbose_name='站内或区间'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field25',
                field=models.CharField(max_length=200, verbose_name='参考标准'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field26',
                field=models.CharField(max_length=200, verbose_name='有无防撞强'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field27',
                field=models.CharField(max_length=200, verbose_name='建筑设备类型'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field28',
                field=models.CharField(max_length=200, verbose_name='核对日期'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field29',
                field=models.CharField(max_length=200, verbose_name='核对人'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field3',
                field=models.CharField(max_length=200, verbose_name='车站及区间名称'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field4',
                field=models.CharField(max_length=200, verbose_name='设备名称'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field5',
                field=models.CharField(max_length=200, verbose_name='公里标'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field6',
                field=models.CharField(max_length=200, verbose_name='本线高度'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field7',
                field=models.CharField(max_length=200, verbose_name='距本线中心线距离(实测值)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field70',
                field=models.CharField(max_length=200, verbose_name='线间距'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field8',
                field=models.CharField(max_length=200, verbose_name='距邻线中心线距离(实测值)'),
                ),
        migrations.AlterField(
                model_name='datatable',
                name='field9',
                field=models.CharField(max_length=200, verbose_name='临线高度'),
                ),
        migrations.AlterField(
                model_name='field1table',
                name='auto_id',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='field1table',
                name='field1',
                field=models.CharField(max_length=200, unique=True, verbose_name='线别'),
                ),
        migrations.AlterField(
                model_name='field23table',
                name='auto_id',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='field23table',
                name='field1',
                field=models.CharField(max_length=200, verbose_name='行别'),
                ),
        migrations.AlterField(
                model_name='field24table',
                name='auto_id',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='field24table',
                name='field1',
                field=models.CharField(max_length=200, verbose_name='站内或区间'),
                ),
        migrations.AlterField(
                model_name='field25table',
                name='auto_id',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='field25table',
                name='field1',
                field=models.CharField(max_length=200, verbose_name='参考标准'),
                ),
        migrations.AlterField(
                model_name='field26table',
                name='auto_id',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='field26table',
                name='field1',
                field=models.CharField(max_length=200, verbose_name='有无防撞强'),
                ),
        migrations.AlterField(
                model_name='field27table',
                name='auto_id',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='field27table',
                name='field1',
                field=models.CharField(max_length=200, verbose_name='建筑设备类型'),
                ),
        migrations.AlterField(
                model_name='field2table',
                name='auto_id',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='field2table',
                name='field1',
                field=models.CharField(max_length=200, unique=True, verbose_name='综合车间'),
                ),
        migrations.AlterField(
                model_name='field3table',
                name='auto_id',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='field3table',
                name='field1',
                field=models.CharField(max_length=200, verbose_name='车站及区间名称'),
                ),
        ]
