# Generated by Django 3.0.7 on 2020-09-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=200)),
                ('field2', models.CharField(max_length=200)),
                ('field3', models.CharField(max_length=200)),
                ('field24', models.CharField(max_length=200)),
                ('field23', models.CharField(max_length=200)),
                ('field46', models.CharField(max_length=200)),
                ('field47', models.CharField(max_length=200)),
                ('field48', models.CharField(max_length=200)),
                ('field49', models.CharField(max_length=200)),
                ('field37', models.CharField(max_length=200)),
                ('field50', models.CharField(max_length=200)),
                ('field51', models.CharField(max_length=200)),
                ('field52', models.CharField(max_length=200)),
                ('field53', models.CharField(max_length=200)),
                ('field54', models.CharField(max_length=200)),
                ('field55', models.CharField(max_length=200)),
                ('field56', models.CharField(max_length=200)),
                ('field57', models.CharField(max_length=200)),
                ('field58', models.CharField(max_length=200)),
                ('field59', models.CharField(max_length=200)),
                ('field60', models.CharField(max_length=200)),
                ('field61', models.CharField(max_length=200)),
                ('field62', models.CharField(max_length=200)),
                ('field63', models.CharField(max_length=200)),
                ('field64', models.CharField(max_length=200)),
                ('field65', models.CharField(max_length=200)),
                ('field66', models.CharField(max_length=200)),
                ('field67', models.CharField(max_length=200)),
                ('field68', models.CharField(max_length=200)),
                ('field69', models.CharField(max_length=200)),
            ],
        ),
    ]
