# Generated by Django 3.0.7 on 2021-03-03 13:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ]

    operations = [
        migrations.CreateModel(
                name='DataTable',
                fields=[
                    ('auto_id',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('field1', models.CharField(max_length=200, verbose_name='线别')),
                    ('field2', models.CharField(max_length=200, verbose_name='车间')),
                    ('field3', models.CharField(max_length=200, verbose_name='车站')),
                    ('field24', models.CharField(max_length=200, verbose_name='站内区间')),
                    ('field23', models.CharField(max_length=200, verbose_name='行别')),
                    ('field46', models.CharField(max_length=200, verbose_name='信号机名称')),
                    ('field48', models.CharField(max_length=200, verbose_name='信号机里程')),
                    ('field47', models.CharField(max_length=200, verbose_name='运营区段名')),
                    ('field49', models.CharField(max_length=200, verbose_name='设计区段名')),
                    ('field37', models.CharField(max_length=200, verbose_name='载频频率')),
                    ('field50', models.CharField(max_length=200, verbose_name='区段长度')),
                    ('field51', models.CharField(max_length=200, verbose_name='段属')),
                    ('field52', models.CharField(max_length=200, verbose_name='备注1')),
                    ('field53', models.CharField(max_length=200, verbose_name='电容规格')),
                    ('field54', models.CharField(max_length=200, verbose_name='电容数量')),
                    ('field55', models.CharField(max_length=200, verbose_name='功出电平理论等级')),
                    ('field56', models.CharField(max_length=200, verbose_name='功出电平理论封线')),
                    ('field57', models.CharField(max_length=200, verbose_name='功出电平变更等级')),
                    ('field58', models.CharField(max_length=200, verbose_name='功出电平变更封线')),
                    ('field59', models.CharField(max_length=200, verbose_name='接收电平理论等级')),
                    ('field60', models.CharField(max_length=200, verbose_name='接收电平理论封线')),
                    ('field61', models.CharField(max_length=200, verbose_name='接收电平变更等级')),
                    ('field62', models.CharField(max_length=200, verbose_name='接收电平变更封线')),
                    ('field63', models.CharField(max_length=200, verbose_name='轨道类型')),
                    ('field64', models.CharField(max_length=200, verbose_name='电缆规定总长度km')),
                    ('field65', models.CharField(max_length=200, verbose_name='发送模拟电缆环阻')),
                    ('field66', models.CharField(max_length=200, verbose_name='发送模拟电缆电缆长度')),
                    ('field67', models.CharField(max_length=200, verbose_name='发送模拟电缆实际电缆长度档位')),
                    ('field68', models.CharField(max_length=200, verbose_name='发送模拟电缆模拟长度')),
                    ('field69', models.CharField(max_length=200, verbose_name='发送模拟电缆模拟固定长度')),
                    ('field71', models.CharField(max_length=200, verbose_name='发送模拟电缆补偿连接线')),
                    ('field72', models.CharField(max_length=200, verbose_name='接收模拟电缆环阻')),
                    ('field73', models.CharField(max_length=200, verbose_name='接收模拟电缆电缆长度')),
                    ('field74', models.CharField(max_length=200, verbose_name='接收模拟电缆实际电缆长度档位')),
                    ('field75', models.CharField(max_length=200, verbose_name='接收模拟电缆模拟长度')),
                    ('field76', models.CharField(max_length=200, verbose_name='接收模拟电缆模拟固定长度')),
                    ('field77', models.CharField(max_length=200, verbose_name='接收模拟电缆补偿连接线')),
                    ('field78', models.CharField(max_length=200, verbose_name='调整表固定区段')),
                    ('field79', models.CharField(max_length=200, verbose_name='有无小轨')),
                    ('field80', models.CharField(max_length=200, verbose_name='小轨调整正向等级')),
                    ('field81', models.CharField(max_length=200, verbose_name='小轨调整正向封线')),
                    ('field82', models.CharField(max_length=200, verbose_name='小轨调整反向等级')),
                    ('field83', models.CharField(max_length=200, verbose_name='小轨调整反向封线')),
                    ('field84', models.CharField(max_length=200, verbose_name='备注2')),
                    ],
                ),
        migrations.CreateModel(
                name='Field71Table',
                fields=[
                    ('auto_id',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('field1', models.CharField(max_length=200, verbose_name='轨道类型')),
                    ('changdu', models.CharField(default='', max_length=100, null=True,
                                                 verbose_name='电缆规定总长度')),
                    ],
                ),
        ]
