# Generated by Django 3.0.7 on 2020-10-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Model3', '0002_auto_20201011_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='field71',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field72',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field73',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field74',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field75',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field76',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field77',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field78',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field79',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field80',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field81',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field82',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field83',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='field84',
            field=models.CharField(max_length=200),
        ),
    ]
