# Generated by Django 3.0.7 on 2020-12-19 05:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ]

    operations = [
        migrations.CreateModel(
                name='ChenJian_CheZhan',
                fields=[
                    ('xuhao', models.AutoField(primary_key=True, serialize=False)),
                    ('chejian', models.CharField(max_length=100, verbose_name='车间')),
                    ('chezhan', models.CharField(max_length=100, verbose_name='车站')),
                    ],
                ),
        migrations.CreateModel(
                name='Luruye',
                fields=[
                    ('xuhao', models.AutoField(primary_key=True, serialize=False)),
                    ('duanbie', models.CharField(max_length=100, verbose_name='段别')),
                    ('xianbie', models.CharField(max_length=100, verbose_name='线别')),
                    ('chejian', models.CharField(max_length=100, verbose_name='车间')),
                    ('chezhan', models.CharField(max_length=100, verbose_name='车站')),
                    ('genbanren', models.CharField(max_length=100, verbose_name='车间跟班人')),
                    ('gongqu', models.CharField(max_length=100, verbose_name='工区')),
                    ('zuoyeren', models.CharField(max_length=100, verbose_name='工区作业人')),
                    ('renwuliang', models.CharField(max_length=100, verbose_name='任务量')),
                    ('xiangmu', models.CharField(max_length=100, verbose_name='项目')),
                    ('feilei', models.CharField(max_length=100, verbose_name='工作内容分类')),
                    ('gongzuoneirong', models.CharField(max_length=100, verbose_name='工作内容')),
                    ('danwei', models.CharField(max_length=100, verbose_name='单位')),
                    ('wanchengshuliang', models.CharField(max_length=100, verbose_name='完成数量')),
                    ('wanchengriqi', models.CharField(max_length=100, verbose_name='完成日期')),
                    ],
                ),
        migrations.CreateModel(
                name='Xiangmu_Gongzuoneirong',
                fields=[
                    ('xuhao', models.AutoField(primary_key=True, serialize=False)),
                    ('gongzuoneirong', models.CharField(max_length=100, verbose_name='工作内容')),
                    ('xiangmu', models.CharField(max_length=100, verbose_name='项目')),
                    ('renwuliang', models.CharField(max_length=100, verbose_name='工作任务量')),
                    ],
                ),
        migrations.CreateModel(
                name='ZhuYe',
                fields=[
                    ('xuhao', models.AutoField(primary_key=True, serialize=False)),
                    ('xiangmu', models.CharField(max_length=100, verbose_name='项目')),
                    ('gongzuoneirong', models.CharField(max_length=100, verbose_name='工作内容')),
                    ('danwei', models.CharField(max_length=100, verbose_name='单位')),
                    ('renwuliang', models.CharField(max_length=100, verbose_name='任务量')),
                    ('benyuewanchen', models.CharField(max_length=100, verbose_name='本月完成数量')),
                    ('leijiwanchen', models.CharField(max_length=100, verbose_name='累计完成数量')),
                    ('chejian', models.CharField(max_length=100, verbose_name='车间')),
                    ('chezhan', models.CharField(max_length=100, verbose_name='车站')),
                    ('create_time', models.CharField(max_length=100, verbose_name='创建时间')),
                    ],
                ),
        ]
