# Generated by Django 3.0.7 on 2020-12-20 08:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0002_auto_20201219_1549'),
        ]

    operations = [
        migrations.AddField(
                model_name='xiangmu_gongzuoneirong',
                name='danwei',
                field=models.CharField(default='', max_length=100, verbose_name='单位'),
                ),
        ]
