# Generated by Django 3.0.7 on 2020-12-28 11:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0003_xiangmu_gongzuoneirong_danwei'),
        ]

    operations = [
        migrations.DeleteModel(
                name='ChenJian_CheZhan',
                ),
        migrations.DeleteModel(
                name='Xiangmu_Gongzuoneirong',
                ),
        migrations.RenameField(
                model_name='luruye',
                old_name='feilei',
                new_name='fenlei',
                ),
        migrations.AlterField(
                model_name='luruye',
                name='xuhao',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        migrations.AlterField(
                model_name='zhuye',
                name='xuhao',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
                ),
        ]
