# Generated by Django 3.0.7 on 2020-12-28 12:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0005_auto_20201228_2027'),
        ]

    operations = [
        migrations.AlterField(
                model_name='zhuye',
                name='fenlei',
                field=models.CharField(max_length=100, verbose_name='工作内容分类'),
                ),
        ]
