# Generated by Django 3.0.7 on 2020-12-29 12:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0006_auto_20201228_2027'),
        ]

    operations = [
        migrations.AlterField(
                model_name='luruye',
                name='chejian',
                field=models.CharField(default='', max_length=100, verbose_name='车间'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='chezhan',
                field=models.CharField(default='', max_length=100, verbose_name='车站'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='danwei',
                field=models.CharField(default='', max_length=100, verbose_name='单位'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='duanbie',
                field=models.CharField(default='', max_length=100, verbose_name='段别'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='fenlei',
                field=models.CharField(default='', max_length=100, verbose_name='工作内容分类'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='genbanren',
                field=models.CharField(default='', max_length=100, verbose_name='车间跟班人'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='gongqu',
                field=models.CharField(default='', max_length=100, verbose_name='工区'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='gongzuoneirong',
                field=models.CharField(default='', max_length=100, verbose_name='工作内容'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='renwuliang',
                field=models.CharField(default='', max_length=100, verbose_name='任务量'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='wanchengriqi',
                field=models.CharField(default='', max_length=100, verbose_name='完成日期'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='wanchengshuliang',
                field=models.CharField(default='', max_length=100, verbose_name='完成数量'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='xianbie',
                field=models.CharField(default='', max_length=100, verbose_name='线别'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='xiangmu',
                field=models.CharField(default='', max_length=100, verbose_name='项目'),
                ),
        migrations.AlterField(
                model_name='luruye',
                name='zuoyeren',
                field=models.CharField(default='', max_length=100, verbose_name='工区作业人'),
                ),
        ]
