# Generated by Django 3.0.7 on 2020-12-30 12:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0008_auto_20201229_2051'),
        ]

    operations = [
        migrations.AlterField(
                model_name='zhuye',
                name='benyuewanchen',
                field=models.CharField(default='', max_length=100, null=True,
                                       verbose_name='本月完成数量'),
                ),
        migrations.AlterField(
                model_name='zhuye',
                name='chejian',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='车间'),
                ),
        migrations.AlterField(
                model_name='zhuye',
                name='chezhan',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='车站'),
                ),
        migrations.AlterField(
                model_name='zhuye',
                name='create_time',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='创建时间'),
                ),
        migrations.AlterField(
                model_name='zhuye',
                name='danwei',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='单位'),
                ),
        migrations.AlterField(
                model_name='zhuye',
                name='fenlei',
                field=models.CharField(default='', max_length=100, null=True,
                                       verbose_name='工作内容分类'),
                ),
        migrations.AlterField(
                model_name='zhuye',
                name='leijiwanchen',
                field=models.CharField(default='', max_length=100, null=True,
                                       verbose_name='累计完成数量'),
                ),
        migrations.AlterField(
                model_name='zhuye',
                name='renwuliang',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='任务量'),
                ),
        migrations.AlterField(
                model_name='zhuye',
                name='xiangmu',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='项目'),
                ),
        ]
