# Generated by Django 3.0.7 on 2021-01-03 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0010_auto_20210103_1808'),
        ]

    operations = [
        migrations.RemoveField(
                model_name='zhuye',
                name='neirongshuoming',
                ),
        migrations.RemoveField(
                model_name='zhuye',
                name='zhouqi',
                ),
        ]
