# Generated by Django 3.0.8 on 2021-01-05 09:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0012_auto_20210103_1908'),
        ]

    operations = [
        migrations.AddField(
                model_name='luruye',
                name='jidu',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='工作月份'),
                ),
        migrations.AddField(
                model_name='zhuye',
                name='jidu',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='工作月份'),
                ),
        ]
