# Generated by Django 3.0.7 on 2021-01-09 14:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0013_auto_20210105_1711'),
        ]

    operations = [
        migrations.AddField(
                model_name='zhuye',
                name='xianbie',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='线别'),
                ),
        ]
