# Generated by Django 3.0.8 on 2021-01-28 08:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0014_zhuye_xianbie'),
        ]

    operations = [
        migrations.CreateModel(
                name='XiangMu',
                fields=[
                    ('xuhao',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('xiangmu',
                     models.CharField(default='', max_length=100, null=True, verbose_name='项目')),
                    ('fenlei', models.CharField(default='', max_length=100, null=True,
                                                verbose_name='工作内容分类')),
                    ('jidu',
                     models.CharField(default='', max_length=100, null=True, verbose_name='工作月份')),
                    ('zhouqi',
                     models.CharField(default='', max_length=100, null=True, verbose_name='工作周期')),
                    ('neirongshuoming', models.CharField(default='', max_length=100, null=True,
                                                         verbose_name='工作要求说明')),
                    ('danwei',
                     models.CharField(default='', max_length=100, null=True, verbose_name='单位')),
                    ],
                ),
        ]
