# Generated by Django 3.0.7 on 2021-02-05 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0015_xiangmu'),
        ]

    operations = [
        migrations.RenameField(
                model_name='luruye',
                old_name='xuhao',
                new_name='auto_id',
                ),
        migrations.RenameField(
                model_name='xiangmu',
                old_name='xuhao',
                new_name='auto_id',
                ),
        migrations.RenameField(
                model_name='zhuye',
                old_name='xuhao',
                new_name='auto_id',
                ),
        ]
