# Generated by Django 3.0.7 on 2021-02-05 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Model5', '0016_auto_20210205_1657'),
        ]

    operations = [
        migrations.RenameField(
                model_name='luruye',
                old_name='jidu',
                new_name='yuefen',
                ),
        migrations.RenameField(
                model_name='xiangmu',
                old_name='jidu',
                new_name='yuefen',
                ),
        migrations.RenameField(
                model_name='zhuye',
                old_name='jidu',
                new_name='yuefen',
                ),
        ]
