# Generated by Django 3.0.7 on 2021-01-21 12:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ]

    operations = [
        migrations.CreateModel(
                name='DataTable',
                fields=[
                    ('auto_id',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('wentiriqi', models.CharField(default='', max_length=100, null=True,
                                                   verbose_name='检测发现问题日期')),
                    ('xianbie',
                     models.CharField(default='', max_length=100, null=True, verbose_name='线别')),
                    ('chejian',
                     models.CharField(default='', max_length=100, null=True, verbose_name='综合车间')),
                    ('chezhan',
                     models.CharField(default='', max_length=100, null=True, verbose_name='车站')),
                    ('quduan',
                     models.CharField(default='', max_length=100, null=True, verbose_name='区段名称')),
                    ('buliangdianrong', models.CharField(default='', max_length=100, null=True,
                                                         verbose_name='发现问题(不良电容)')),
                    ('hangbie',
                     models.CharField(default='', max_length=100, null=True, verbose_name='行别')),
                    ('dianrongshuliang', models.CharField(default='', max_length=100, null=True,
                                                          verbose_name='本区段电容数量')),
                    ('zaiping',
                     models.CharField(default='', max_length=100, null=True, verbose_name='本区段载频')),
                    ('chuliriqi',
                     models.CharField(default='', max_length=100, null=True, verbose_name='处理日期')),
                    ('yuanying',
                     models.CharField(default='', max_length=100, null=True, verbose_name='问题原因')),
                    ('chuliqingkuang',
                     models.CharField(default='', max_length=100, null=True, verbose_name='处理情况')),
                    ('shangbaoqingkuang',
                     models.CharField(default='', max_length=100, null=True, verbose_name='上报情况')),
                    ('zhouqi',
                     models.CharField(default='', max_length=100, null=True, verbose_name='周期')),
                    ('beizhu',
                     models.CharField(default='', max_length=100, null=True, verbose_name='备注')),
                    ('qiandianliu', models.CharField(default='', max_length=100, null=True,
                                                     verbose_name='整改前电流(A)')),
                    ('houdianliu', models.CharField(default='', max_length=100, null=True,
                                                    verbose_name='整改后电流(A)')),
                    ('qiandianya', models.CharField(default='', max_length=100, null=True,
                                                    verbose_name='整改前电压(V)')),
                    ('houdianya', models.CharField(default='', max_length=100, null=True,
                                                   verbose_name='整改后电压(V)')),
                    ('qiandianrong', models.CharField(default='', max_length=100, null=True,
                                                      verbose_name='整改前容值(uf)')),
                    ('houdianrong', models.CharField(default='', max_length=100, null=True,
                                                     verbose_name='整改后容值(uf)')),
                    ('changjia',
                     models.CharField(default='', max_length=100, null=True, verbose_name='生产厂家')),
                    ('shiyongshijian', models.CharField(default='', max_length=100, null=True,
                                                        verbose_name='使用时间(年)')),
                    ('fankuiren',
                     models.CharField(default='', max_length=100, null=True, verbose_name='反馈人')),
                    ],
                ),
        ]
