# Generated by Django 3.0.8 on 2021-01-24 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Model8', '0002_changjia'),
        ]

    operations = [
        migrations.DeleteModel(
                name='ChangJia',
                ),
        ]
