# Generated by Django 3.0.8 on 2021-01-29 09:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model8', '0003_delete_changjia'),
        ]

    operations = [
        migrations.CreateModel(
                name='QuDuanTable',
                fields=[
                    ('auto_id',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('xianbie',
                     models.CharField(default='', max_length=100, null=True, verbose_name='线别')),
                    ('chezhan',
                     models.CharField(default='', max_length=100, null=True, verbose_name='车站')),
                    ('quduan',
                     models.CharField(default='', max_length=100, null=True, verbose_name='区段名称')),
                    ('zaiping',
                     models.CharField(default='', max_length=100, null=True, verbose_name='载频')),
                    ('dianrongshuliang',
                     models.CharField(default='', max_length=100, null=True, verbose_name='电容数量')),
                    ('hangbie',
                     models.CharField(default='', max_length=100, null=True, verbose_name='行别')),
                    ('quduanchangdu',
                     models.CharField(default='', max_length=100, null=True, verbose_name='区段长度')),
                    ],
                ),
        migrations.AlterField(
                model_name='datatable',
                name='zaiping',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='载频'),
                ),
        ]
