# Generated by Django 3.0.7 on 2021-02-05 08:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model8', '0004_auto_20210129_1707'),
        ]

    operations = [
        migrations.AlterField(
                model_name='quduantable',
                name='chezhan',
                field=models.CharField(blank=True, default='', max_length=100, null=True,
                                       verbose_name='车站'),
                ),
        migrations.AlterField(
                model_name='quduantable',
                name='dianrongshuliang',
                field=models.CharField(blank=True, default='', max_length=100, null=True,
                                       verbose_name='电容数量'),
                ),
        migrations.AlterField(
                model_name='quduantable',
                name='hangbie',
                field=models.CharField(blank=True, default='', max_length=100, null=True,
                                       verbose_name='行别'),
                ),
        migrations.AlterField(
                model_name='quduantable',
                name='quduan',
                field=models.CharField(blank=True, default='', max_length=100, null=True,
                                       verbose_name='区段名称'),
                ),
        migrations.AlterField(
                model_name='quduantable',
                name='quduanchangdu',
                field=models.CharField(blank=True, default='', max_length=100, null=True,
                                       verbose_name='区段长度'),
                ),
        migrations.AlterField(
                model_name='quduantable',
                name='xianbie',
                field=models.CharField(blank=True, default='', max_length=100, null=True,
                                       verbose_name='线别'),
                ),
        migrations.AlterField(
                model_name='quduantable',
                name='zaiping',
                field=models.CharField(blank=True, default='', max_length=100, null=True,
                                       verbose_name='载频'),
                ),
        ]
