# Generated by Django 3.0.8 on 2020-11-03 07:54

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ]

    operations = [
        migrations.CreateModel(
                name='ExamArea',
                fields=[
                    ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                    ('name', models.CharField(max_length=100)),
                    ],
                options={
                    'db_table': 'ExamArea',
                    },
                ),
        migrations.CreateModel(
                name='Faculty',
                fields=[
                    ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                    ('name', models.CharField(max_length=100)),
                    ],
                options={
                    'db_table': 'Faculty',
                    },
                ),
        migrations.CreateModel(
                name='Language',
                fields=[
                    ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                    ('name', models.CharField(max_length=100)),
                    ],
                options={
                    'db_table': 'ForeignLanguages',
                    },
                ),
        migrations.CreateModel(
                name='Nationality',
                fields=[
                    ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                    ('name', models.CharField(max_length=100)),
                    ],
                options={
                    'db_table': 'Nationality',
                    },
                ),
        migrations.CreateModel(
                name='Sex',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')])),
                    ],
                options={
                    'db_table': 'Sex',
                    },
                ),
        migrations.CreateModel(
                name='BasicInfo',
                fields=[
                    ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                    ('name', models.CharField(max_length=50)),
                    ('class_name', models.CharField(max_length=50)),
                    ('into_date', models.DateField()),
                    ('birthday', models.DateField()),
                    ('grade', models.IntegerField()),
                    ('email', models.EmailField(max_length=254)),
                    ('exam_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                       to='app.ExamArea')),
                    ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                     to='app.Faculty')),
                    ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                      to='app.Language')),
                    ('nationality',
                     models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                          to='app.Nationality')),
                    ('sex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                 to='app.Sex')),
                    ],
                options={
                    'db_table': 'BasicInfo',
                    },
                ),
        ]
