# Generated by Django 3.0.8 on 2020-12-15 06:14

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
        ]
    atomic = False
    operations = [
        migrations.RemoveField(
                model_name='sex',
                name='id',
                ),
        migrations.AddField(
                model_name='sex',
                name='number',
                field=models.AutoField(default=2, primary_key=True, serialize=False,
                                       verbose_name='编号'),
                preserve_default=False,
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='birthday',
                field=models.DateField(verbose_name='出生日期'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='class_name',
                field=models.CharField(max_length=50, verbose_name='班级'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='email',
                field=models.EmailField(max_length=254, verbose_name='邮箱'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='exam_area',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                        to='app.ExamArea', verbose_name='考区'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='faculty',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                        to='app.Faculty', verbose_name='学院'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='grade',
                field=models.FloatField(verbose_name='分数'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='into_date',
                field=models.DateField(verbose_name='入学时间'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='language',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                        to='app.Language', verbose_name='语种'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='name',
                field=models.CharField(max_length=50, verbose_name='姓名'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='nationality',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                        to='app.Nationality', verbose_name='名族'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='number',
                field=models.CharField(max_length=10, primary_key=True, serialize=False,
                                       verbose_name='学号'),
                ),
        migrations.AlterField(
                model_name='basicinfo',
                name='sex',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sex',
                                        verbose_name='性别'),
                ),
        migrations.AlterField(
                model_name='examarea',
                name='name',
                field=models.CharField(max_length=100, unique=True, verbose_name='考区名称'),
                ),
        migrations.AlterField(
                model_name='examarea',
                name='number',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='考区编号'),
                ),
        migrations.AlterField(
                model_name='faculty',
                name='name',
                field=models.CharField(default='', max_length=100, unique=True,
                                       verbose_name='学院名称'),
                ),
        migrations.AlterField(
                model_name='faculty',
                name='number',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='学院编号'),
                ),
        migrations.AlterField(
                model_name='language',
                name='name',
                field=models.CharField(max_length=100, unique=True, verbose_name='语种名称'),
                ),
        migrations.AlterField(
                model_name='language',
                name='number',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='语种编号'),
                ),
        migrations.AlterField(
                model_name='nationality',
                name='name',
                field=models.CharField(max_length=100, unique=True, verbose_name='名族名称'),
                ),
        migrations.AlterField(
                model_name='nationality',
                name='number',
                field=models.AutoField(primary_key=True, serialize=False, verbose_name='名族编号'),
                ),
        migrations.AlterField(
                model_name='sex',
                name='gender',
                field=models.CharField(default='', max_length=10, unique=True, verbose_name='性别'),
                ),
        migrations.AlterModelTable(
                name='faculty',
                table='XueYuan',
                ),
        ]
