# Generated by Django 3.0.8 on 2020-12-15 06:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_auto_20201215_1414'),
        ]

    operations = [
        migrations.AlterField(
                model_name='faculty',
                name='name',
                field=models.CharField(blank=True, default='', max_length=100, unique=True,
                                       verbose_name='学院名称'),
                ),
        ]
