# Generated by Django 3.0.7 on 2021-01-17 07:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model7', '0002_auto_20210117_1552'),
        ]

    operations = [
        migrations.AlterField(
                model_name='xianbiechejian',
                name='chejian',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='综合车间'),
                ),
        migrations.AlterField(
                model_name='xianbiechejian',
                name='xianbie',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='线别'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='beizhu',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='备注'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='bianhao',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='出产编号'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='caozuo',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='操作'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='changjia',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='制造厂家'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='chejian',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='综合车间'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='dangqianzhuangtai',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='当前状态'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='dengji',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='准确度等级'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='didian',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='使用地点'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='fanwei',
                field=models.CharField(default='', max_length=100, null=True,
                                       verbose_name='测量范围(mm)'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='fuzeren',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='保管负责人'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='guige',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='规格型号'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='mingcheng',
                field=models.CharField(default='', max_length=100, null=True,
                                       verbose_name='计量器具名称'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='riqi',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='检定日期'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='xiaciriqi',
                field=models.CharField(default='', max_length=100, null=True,
                                       verbose_name='下次检定日期'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='xianbie',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='线别'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='yibiaozhuangtai',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='仪表状态'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='zhouqi',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='检定周期'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='zhuanye',
                field=models.CharField(default='', max_length=100, null=True, verbose_name='专业'),
                ),
        migrations.AlterField(
                model_name='yiqiyibiaotaizhang',
                name='zongcheng',
                field=models.CharField(default='', max_length=100, null=True,
                                       verbose_name='计量器具总称'),
                ),
        ]
