# Generated by Django 3.0.8 on 2021-01-23 03:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model7', '0004_auto_20210121_2052'),
        ]

    operations = [
        migrations.CreateModel(
                name='JiandingZhouqi',
                fields=[
                    ('auto_id',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('name', models.CharField(default='', max_length=100, null=True, unique=True,
                                              verbose_name='检定周期')),
                    ],
                ),
        migrations.CreateModel(
                name='JiliangQiju',
                fields=[
                    ('auto_id',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('name', models.CharField(default='', max_length=100, null=True, unique=True,
                                              verbose_name='计量器具总称')),
                    ],
                ),
        ]
