# Generated by Django 3.0.8 on 2021-01-23 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Model7', '0005_jiandingzhouqi_jiliangqiju'),
        ]

    operations = [
        migrations.RenameField(
                model_name='jiandingzhouqi',
                old_name='name',
                new_name='zhouqi',
                ),
        migrations.RenameField(
                model_name='jiliangqiju',
                old_name='name',
                new_name='zongcheng',
                ),
        ]
