# Generated by Django 3.0.8 on 2021-01-24 08:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model7', '0006_auto_20210123_1551'),
        ]

    operations = [
        migrations.CreateModel(
                name='DangqianZhuangtai',
                fields=[
                    ('auto_id',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('dangqianzhuangtai',
                     models.CharField(default='', max_length=100, null=True, verbose_name='当前状态')),
                    ],
                ),
        migrations.CreateModel(
                name='DiDian',
                fields=[
                    ('auto_id',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('didian',
                     models.CharField(default='', max_length=100, null=True, verbose_name='使用地点')),
                    ],
                ),
        migrations.RemoveField(
                model_name='datatable',
                name='caozuo',
                ),
        ]
