# Generated by Django 3.0.8 on 2021-01-24 08:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('Model7', '0007_auto_20210124_1602'),
        ]

    operations = [
        migrations.CreateModel(
                name='ChangJia',
                fields=[
                    ('auto_id',
                     models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                    ('changjia',
                     models.CharField(default='', max_length=100, null=True, verbose_name='生产厂家')),
                    ],
                ),
        ]
